jobs:
  build:
    name: Workflow
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Pull Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./action/check

name: Ci

on:
  schedule:
    - cron: "40 */6 * * *"
